### ISSUE TITLE
Need help to compile the kernel

### ISSUE THREAD

**Issue by ghojeong** [ucsdsysnet/faasnap-kernel#1]
I have following error message while compiling the kernel.
What can I do to solve this problem?

![스크린샷 2022-09-17 오후 3 58 06](https://user-images.githubusercontent.com/38595650/190844804-39695c5f-7a58-46ad-9885-016e07ac38c2.png)

**Comment by lihshyang** [comment]
One workaround is to remove the `-Werror=restrict` flag

**Comment by ghojeong** [comment]
Solved the problem.
Thanks!
I will close this issue.
